sudo: false
language: python
branches:
  only:
  - master
  - devel

matrix:
  include:
  - python: "2.7"
    env: PACKAGES="mock numpy"
  - python: "3.4"
    env: PACKAGES="numpy"
  - python: "3.5"
    env: PACKAGES="numpy"
  - python: "3.6"
    env: PACKAGES="numpy"
  - python: "3.7"
    env: PACKAGES="numpy"
  - python: "3.8"
    env: PACKAGES="numpy"
  - python: "pypy"
    env: PACKAGES="mock"; NUMPY="git+https://bitbucket.org/pypy/numpy.git"
  - python: "3.7"
    name: "Flake8"
    dist: xenial
    env: PACKAGES="numpy flake8"; FLAKE8=1

addons:
  apt:
    packages:
    - gfortran
    - libblas-dev
    - liblapack-dev

# command to install dependencies and translate deap in py3k
install:
  - |
      if [ "$TRAVIS_PYTHON_VERSION" = "pypy" ]; then
        export PYENV_ROOT="$HOME/.pyenv"
        if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
          cd "$PYENV_ROOT" && git pull
        else
          rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
        fi
        export PYPY_VERSION="4.0.1"
        "$PYENV_ROOT/bin/pyenv" install "pypy-$PYPY_VERSION"
        virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
        source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
        PACKAGES="$PACKAGES $NUMPY@pypy-4.0.1"
      fi
  - pip install -U nose
  - pip install -U $PACKAGES

# command to run tests
script:
  - |
      if [[ -z "${FLAKE8}" ]]; then
        python setup.py nosetests --verbosity=3 --with-doctest
      else
        flake8
      fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f17745fc250ffb09c0e9
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
